import { RoleScoringCriteria, GradeTaskItem, GradeRequirement } from '@types/scoring';
import { Role } from '@types/game';

const GRADE_REQUIREMENTS = {
  bronze: { grade: 'bronze', minScore: 7, maxScore: 9, emoji: '🥉', label: '铜牌评分' },
  silver: { grade: 'silver', minScore: 9, maxScore: 12, emoji: '🥈', label: '银牌评分' },
  gold: { grade: 'gold', minScore: 12, maxScore: 14, emoji: '🥇', label: '金牌评分' },
  top: { grade: 'top', minScore: 14, maxScore: 16, emoji: '👑', label: '顶级评分' },
};

const EXP_LANE_TASKS: RoleScoringCriteria = {
  role: 'exp_lane',
  gradeRequirements: GRADE_REQUIREMENTS,
  dimensionWeights: [
    { dimension: 'damage', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
    { dimension: 'survival', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'teamfight', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'farm', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'kda', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
  ],
  increaseTasks: [
    // ========== 铜牌任务 ==========
    {
      id: 'exp_bronze_kill',
      description: '完成击杀',
      requirement: '击杀敌方英雄',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'exp_bronze_solo_kill',
      description: '完成单杀',
      requirement: '单杀敌方英雄≥1次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.8,
      critical: false,
    },
    {
      id: 'exp_bronze_turret',
      description: '推塔贡献',
      requirement: '推塔数≥1座',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'exp_bronze_assist',
      description: '参与击杀',
      requirement: '助攻数≥3次',
      type: 'increase',
      weight: 1.5,
      scoreBonus: 0.3,
      critical: false,
    },
    {
      id: 'exp_bronze_low_death',
      description: '保持存活',
      requirement: '死亡次数≤4次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.4,
      critical: false,
    },
    // ========== 银牌任务 ==========
    {
      id: 'exp_silver_kill',
      description: '多次击杀',
      requirement: '击杀数≥3次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'exp_silver_solo_kill',
      description: '多次单杀',
      requirement: '单杀次数≥2次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'exp_silver_turret',
      description: '推塔贡献',
      requirement: '推塔数≥2座',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'exp_silver_teamfight',
      description: '积极参团',
      requirement: '参团率≥50%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'exp_silver_assist',
      description: '较多助攻',
      requirement: '助攻数≥5次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.4,
      critical: false,
    },
    {
      id: 'exp_silver_low_death',
      description: '保持存活',
      requirement: '死亡次数≤3次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: true,
    },
    {
      id: 'exp_silver_farm',
      description: '经济领先',
      requirement: '经济排名≥3位',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.4,
      critical: false,
    },
    // ========== 金牌任务 ==========
    {
      id: 'exp_gold_kill',
      description: '高击杀数',
      requirement: '击杀数≥5次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'exp_gold_solo_kill',
      description: '多次单杀',
      requirement: '单杀次数≥2次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'exp_gold_turret',
      description: '大量推塔',
      requirement: '推塔数≥2座',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'exp_gold_teamfight',
      description: '高参团率',
      requirement: '参团率≥60%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'exp_gold_kda',
      description: '优秀KDA',
      requirement: 'KDA≥5.0',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'exp_gold_damage_tank',
      description: '坦克承伤',
      requirement: '承伤占比≥30%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: false,
    },
    {
      id: 'exp_gold_damage_warrior',
      description: '战士输出',
      requirement: '输出占比≥25%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: false,
    },
    {
      id: 'exp_gold_low_death',
      description: '极低死亡',
      requirement: '死亡次数≤2次',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: true,
    },
    // ========== 顶级任务 ==========
    {
      id: 'exp_top_kill',
      description: '超高击杀',
      requirement: '击杀数≥7次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.5,
      critical: true,
    },
    {
      id: 'exp_top_solo_kill',
      description: '大量单杀',
      requirement: '单杀次数≥3次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'exp_top_turret',
      description: '大量推塔',
      requirement: '推塔数≥3座',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'exp_top_teamfight',
      description: '极高参团率',
      requirement: '参团率≥70%',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'exp_top_kda',
      description: '顶级KDA',
      requirement: 'KDA≥8.0',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'exp_top_low_death',
      description: '极少死亡',
      requirement: '死亡次数≤1次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'exp_top_first_kill',
      description: '一血贡献',
      requirement: '参与一血',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: false,
    },
  ],
  decreaseTasks: [
    {
      id: 'exp_death_penalty',
      description: '死亡过多',
      requirement: '死亡次数>5次',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.5,
      critical: false,
    },
    {
      id: 'exp_low_participation',
      description: '参团率低',
      requirement: '参团率<30%',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.4,
      critical: false,
    },
    {
      id: 'exp_low_farm',
      description: '经济落后',
      requirement: '经济排名<4位',
      type: 'decrease',
      weight: 1.5,
      scoreBonus: -0.3,
      critical: false,
    },
    {
      id: 'exp_no_kill',
      description: '零击杀',
      requirement: '击杀数=0',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.8,
      critical: true,
    },
    {
      id: 'exp_high_death',
      description: '死亡爆炸',
      requirement: '死亡次数>7次',
      type: 'decrease',
      weight: 3,
      scoreBonus: -1.2,
      critical: true,
    },
    {
      id: 'exp_no_turret',
      description: '零推塔',
      requirement: '推塔数=0',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.5,
      critical: false,
    },
  ],
};

const JUNGLE_TASKS: RoleScoringCriteria = {
  role: 'jungle',
  gradeRequirements: GRADE_REQUIREMENTS,
  dimensionWeights: [
    { dimension: 'damage', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
    { dimension: 'survival', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'teamfight', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'farm', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'kda', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
  ],
  increaseTasks: [
    // ========== 铜牌任务 ==========
    {
      id: 'jungle_bronze_kill',
      description: '完成击杀',
      requirement: '击杀+助攻≥8次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'jungle_bronze_gank',
      description: '成功gank',
      requirement: '成功gank≥2次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: false,
    },
    {
      id: 'jungle_bronze_dragon',
      description: '击杀小龙',
      requirement: '击杀龙≥1条',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'jungle_bronze_low_death',
      description: '保持存活',
      requirement: '死亡次数≤4次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.4,
      critical: false,
    },
    {
      id: 'jungle_bronze_teamfight',
      description: '参团贡献',
      requirement: '参团率≥40%',
      type: 'increase',
      weight: 1.5,
      scoreBonus: 0.3,
      critical: false,
    },
    // ========== 银牌任务 ==========
    {
      id: 'jungle_silver_kill',
      description: '较多击杀',
      requirement: '击杀+助攻≥12次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'jungle_silver_gank',
      description: '频繁gank',
      requirement: '成功gank≥4次',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'jungle_silver_dragon',
      description: '控龙',
      requirement: '击杀龙≥2条',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'jungle_silver_teamfight',
      description: '积极参团',
      requirement: '参团率≥50%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'jungle_silver_low_death',
      description: '保持存活',
      requirement: '死亡次数≤3次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: true,
    },
    {
      id: 'jungle_silver_counter_jungle',
      description: '反野',
      requirement: '反野次数≥2次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    // ========== 金牌任务 ==========
    {
      id: 'jungle_gold_kill',
      description: '高击杀贡献',
      requirement: '击杀+助攻≥15次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'jungle_gold_gank',
      description: '高效gank',
      requirement: '成功gank≥5次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'jungle_gold_dragon',
      description: '大量控龙',
      requirement: '击杀龙≥2条',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'jungle_gold_teamfight',
      description: '高参团率',
      requirement: '参团率≥60%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'jungle_gold_low_death',
      description: '极低死亡',
      requirement: '死亡次数≤2次',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'jungle_gold_counter_jungle',
      description: '频繁反野',
      requirement: '反野次数≥3次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: false,
    },
    {
      id: 'jungle_gold_first_blood',
      description: '一血贡献',
      requirement: '参与一血',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: false,
    },
    // ========== 顶级任务 ==========
    {
      id: 'jungle_top_kill',
      description: '超高击杀',
      requirement: '击杀+助攻≥20次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.5,
      critical: true,
    },
    {
      id: 'jungle_top_gold_rank',
      description: '经济领先',
      requirement: '经济排名≥2位',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'jungle_top_dragon',
      description: '完美控龙',
      requirement: '击杀龙≥3条',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'jungle_top_teamfight',
      description: '极高参团率',
      requirement: '参团率≥70%',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'jungle_top_counter_jungle',
      description: '大量反野',
      requirement: '反野次数≥5次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'jungle_top_low_death',
      description: '极少死亡',
      requirement: '死亡次数≤1次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'jungle_top_kda',
      description: '顶级KDA',
      requirement: 'KDA≥8.0',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
  ],
  decreaseTasks: [
    {
      id: 'jungle_death_penalty',
      description: '死亡过多',
      requirement: '死亡次数>5次',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.5,
      critical: false,
    },
    {
      id: 'jungle_low_participation',
      description: '参团率低',
      requirement: '参团率<40%',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.4,
      critical: false,
    },
    {
      id: 'jungle_no_gank',
      description: '零gank',
      requirement: '成功gank=0',
      type: 'decrease',
      weight: 3,
      scoreBonus: -0.9,
      critical: true,
    },
    {
      id: 'jungle_no_dragon',
      description: '零控龙',
      requirement: '击杀龙=0',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.7,
      critical: true,
    },
    {
      id: 'jungle_high_death',
      description: '死亡爆炸',
      requirement: '死亡次数>7次',
      type: 'decrease',
      weight: 3,
      scoreBonus: -1.2,
      critical: true,
    },
    {
      id: 'jungle_low_farm',
      description: '经济落后',
      requirement: '经济排名<3位',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.5,
      critical: false,
    },
  ],
};

const MID_LANE_TASKS: RoleScoringCriteria = {
  role: 'mid_lane',
  gradeRequirements: GRADE_REQUIREMENTS,
  dimensionWeights: [
    { dimension: 'damage', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
    { dimension: 'survival', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'teamfight', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'farm', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'kda', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
  ],
  increaseTasks: [
    // ========== 铜牌任务 ==========
    {
      id: 'mid_bronze_kill',
      description: '完成击杀',
      requirement: '击杀数≥2次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'mid_bronze_assist',
      description: '较多助攻',
      requirement: '助攻数≥3次',
      type: 'increase',
      weight: 1.5,
      scoreBonus: 0.3,
      critical: false,
    },
    {
      id: 'mid_bronze_support',
      description: '边路支援',
      requirement: '支援成功≥2次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: false,
    },
    {
      id: 'mid_bronze_damage',
      description: '输出贡献',
      requirement: '输出占比≥20%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'mid_bronze_low_death',
      description: '保持存活',
      requirement: '死亡次数≤4次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.4,
      critical: false,
    },
    // ========== 银牌任务 ==========
    {
      id: 'mid_silver_kill',
      description: '多次击杀',
      requirement: '击杀数≥4次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'mid_silver_assist',
      description: '高助攻数',
      requirement: '助攻数≥6次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'mid_silver_support',
      description: '频繁支援',
      requirement: '支援成功≥4次',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'mid_silver_damage',
      description: '较高输出',
      requirement: '输出占比≥25%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'mid_silver_teamfight',
      description: '积极参团',
      requirement: '参团率≥55%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'mid_silver_low_death',
      description: '保持存活',
      requirement: '死亡次数≤3次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: true,
    },
    // ========== 金牌任务 ==========
    {
      id: 'mid_gold_kill',
      description: '高击杀数',
      requirement: '击杀数≥6次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'mid_gold_assist',
      description: '极高助攻',
      requirement: '助攻数≥8次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: false,
    },
    {
      id: 'mid_gold_support',
      description: '高效支援',
      requirement: '支援成功≥5次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'mid_gold_damage',
      description: '高输出',
      requirement: '输出占比≥30%',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'mid_gold_teamfight',
      description: '高参团率',
      requirement: '参团率≥65%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'mid_gold_low_death',
      description: '极低死亡',
      requirement: '死亡次数≤2次',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'mid_gold_kda',
      description: '优秀KDA',
      requirement: 'KDA≥6.0',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    // ========== 顶级任务 ==========
    {
      id: 'mid_top_kill',
      description: '超高击杀',
      requirement: '击杀数≥8次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.5,
      critical: true,
    },
    {
      id: 'mid_top_kda',
      description: '顶级KDA',
      requirement: 'KDA≥9.0',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'mid_top_damage',
      description: '超高输出',
      requirement: '输出占比≥35%',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'mid_top_teamfight',
      description: '极高参团率',
      requirement: '参团率≥75%',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'mid_top_low_death',
      description: '极少死亡',
      requirement: '死亡次数≤1次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'mid_top_assist',
      description: '超高助攻',
      requirement: '助攻数≥12次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: false,
    },
    {
      id: 'mid_top_first_kill',
      description: '一血贡献',
      requirement: '参与一血',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: false,
    },
  ],
  decreaseTasks: [
    {
      id: 'mid_death_penalty',
      description: '死亡过多',
      requirement: '死亡次数>5次',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.5,
      critical: false,
    },
    {
      id: 'mid_low_participation',
      description: '参团率低',
      requirement: '参团率<45%',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.4,
      critical: false,
    },
    {
      id: 'mid_low_damage',
      description: '输出不足',
      requirement: '输出占比<20%',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.6,
      critical: true,
    },
    {
      id: 'mid_no_kill',
      description: '零击杀',
      requirement: '击杀数=0',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.8,
      critical: true,
    },
    {
      id: 'mid_no_support',
      description: '不支援',
      requirement: '支援次数=0',
      type: 'decrease',
      weight: 3,
      scoreBonus: -0.9,
      critical: true,
    },
    {
      id: 'mid_high_death',
      description: '死亡爆炸',
      requirement: '死亡次数>7次',
      type: 'decrease',
      weight: 3,
      scoreBonus: -1.2,
      critical: true,
    },
  ],
};

const ROAM_TASKS: RoleScoringCriteria = {
  role: 'roam',
  gradeRequirements: GRADE_REQUIREMENTS,
  dimensionWeights: [
    { dimension: 'damage', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'survival', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
    { dimension: 'teamfight', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
    { dimension: 'farm', weight: 1.5, bronze: 0.8, silver: 1.2, gold: 1.5, top: 2.0 },
    { dimension: 'kda', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
  ],
  increaseTasks: [
    // ========== 铜牌任务 ==========
    {
      id: 'roam_bronze_assist',
      description: '完成助攻',
      requirement: '助攻数≥4次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'roam_bronze_vision',
      description: '布置视野',
      requirement: '视野得分≥20',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'roam_bronze_control',
      description: '提供控制',
      requirement: '控制时长≥15秒',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'roam_bronze_protect',
      description: '保护队友',
      requirement: '保护成功率≥50%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'roam_bronze_low_death',
      description: '保持存活',
      requirement: '死亡次数≤5次',
      type: 'increase',
      weight: 1.5,
      scoreBonus: 0.3,
      critical: false,
    },
    // ========== 银牌任务 ==========
    {
      id: 'roam_silver_assist',
      description: '较多助攻',
      requirement: '助攻数≥6次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'roam_silver_vision',
      description: '较多视野',
      requirement: '视野得分≥30',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'roam_silver_control',
      description: '充足控制',
      requirement: '控制时长≥20秒',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'roam_silver_teamfight',
      description: '积极参团',
      requirement: '参团率≥65%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'roam_silver_heal',
      description: '治疗/护盾',
      requirement: '治疗量≥20%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'roam_silver_low_death',
      description: '保持存活',
      requirement: '死亡次数≤4次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: true,
    },
    // ========== 金牌任务 ==========
    {
      id: 'roam_gold_assist',
      description: '高助攻数',
      requirement: '助攻数≥8次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'roam_gold_vision',
      description: '优秀视野',
      requirement: '视野得分≥35',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'roam_gold_control',
      description: '优秀控制',
      requirement: '控制时长≥25秒',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'roam_gold_teamfight',
      description: '高参团率',
      requirement: '参团率≥75%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'roam_gold_heal',
      description: '大量治疗',
      requirement: '治疗量≥25%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: false,
    },
    {
      id: 'roam_gold_protect',
      description: '完美保护',
      requirement: '保护成功率≥70%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: false,
    },
    {
      id: 'roam_gold_low_death',
      description: '极低死亡',
      requirement: '死亡次数≤3次',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: true,
    },
    // ========== 顶级任务 ==========
    {
      id: 'roam_top_assist',
      description: '超高助攻',
      requirement: '助攻数≥12次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'roam_top_vision',
      description: '完美视野',
      requirement: '视野得分≥45',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'roam_top_control',
      description: '完美控制',
      requirement: '控制时长≥30秒',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'roam_top_teamfight',
      description: '极高参团率',
      requirement: '参团率≥85%',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'roam_top_low_death',
      description: '极少死亡',
      requirement: '死亡次数≤2次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'roam_top_save',
      description: '救死扶伤',
      requirement: '关键保护≥3次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: false,
    },
    {
      id: 'roam_top_kill',
      description: '击杀贡献',
      requirement: '击杀+助攻≥18次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: false,
    },
  ],
  decreaseTasks: [
    {
      id: 'roam_death_penalty',
      description: '死亡过多',
      requirement: '死亡次数>6次',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.5,
      critical: false,
    },
    {
      id: 'roam_low_participation',
      description: '参团率低',
      requirement: '参团率<50%',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.4,
      critical: false,
    },
    {
      id: 'roam_no_vision',
      description: '不布视野',
      requirement: '视野得分<15',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.7,
      critical: true,
    },
    {
      id: 'roam_no_control',
      description: '零控制',
      requirement: '控制时长=0',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.6,
      critical: true,
    },
    {
      id: 'roam_high_death',
      description: '死亡爆炸',
      requirement: '死亡次数>8次',
      type: 'decrease',
      weight: 3,
      scoreBonus: -1.2,
      critical: true,
    },
    {
      id: 'roam_no_assist',
      description: '零助攻',
      requirement: '助攻数<2',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.7,
      critical: true,
    },
  ],
};

const GOLD_LANE_TASKS: RoleScoringCriteria = {
  role: 'gold_lane',
  gradeRequirements: GRADE_REQUIREMENTS,
  dimensionWeights: [
    { dimension: 'damage', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
    { dimension: 'survival', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'teamfight', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'farm', weight: 2.0, bronze: 1.0, silver: 1.5, gold: 2.0, top: 2.5 },
    { dimension: 'kda', weight: 2.5, bronze: 1.5, silver: 2.0, gold: 2.5, top: 3.0 },
  ],
  increaseTasks: [
    // ========== 铜牌任务 ==========
    {
      id: 'gold_bronze_kill',
      description: '完成击杀',
      requirement: '击杀数≥2次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'gold_bronze_turret',
      description: '推塔贡献',
      requirement: '推塔数≥1座',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: true,
    },
    {
      id: 'gold_bronze_assist',
      description: '参与助攻',
      requirement: '助攻数≥2次',
      type: 'increase',
      weight: 1.5,
      scoreBonus: 0.3,
      critical: false,
    },
    {
      id: 'gold_bronze_damage',
      description: '输出贡献',
      requirement: '输出占比≥18%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'gold_bronze_low_death',
      description: '保持存活',
      requirement: '死亡次数≤3次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.4,
      critical: false,
    },
    // ========== 银牌任务 ==========
    {
      id: 'gold_silver_kill',
      description: '多次击杀',
      requirement: '击杀数≥4次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'gold_silver_turret',
      description: '推塔贡献',
      requirement: '推塔数≥2座',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'gold_silver_damage',
      description: '较高输出',
      requirement: '输出占比≥22%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'gold_silver_teamfight',
      description: '积极参团',
      requirement: '参团率≥50%',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.5,
      critical: false,
    },
    {
      id: 'gold_silver_assist',
      description: '较多助攻',
      requirement: '助攻数≥4次',
      type: 'increase',
      weight: 2,
      scoreBonus: 0.4,
      critical: false,
    },
    {
      id: 'gold_silver_low_death',
      description: '保持存活',
      requirement: '死亡次数≤2次',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.6,
      critical: true,
    },
    // ========== 金牌任务 ==========
    {
      id: 'gold_gold_kill',
      description: '高击杀数',
      requirement: '击杀数≥6次',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'gold_gold_turret',
      description: '大量推塔',
      requirement: '推塔数≥3座',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'gold_gold_damage',
      description: '高输出',
      requirement: '输出占比≥25%',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'gold_gold_teamfight',
      description: '高参团率',
      requirement: '参团率≥60%',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: true,
    },
    {
      id: 'gold_gold_kda',
      description: '优秀KDA',
      requirement: 'KDA≥6.0',
      type: 'increase',
      weight: 3,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'gold_gold_low_death',
      description: '极低死亡',
      requirement: '死亡次数≤2次',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: true,
    },
    {
      id: 'gold_gold_farm',
      description: '优秀发育',
      requirement: '经济排名≥2位',
      type: 'increase',
      weight: 2.5,
      scoreBonus: 0.7,
      critical: false,
    },
    // ========== 顶级任务 ==========
    {
      id: 'gold_top_kill',
      description: '超高击杀',
      requirement: '击杀数≥8次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.5,
      critical: true,
    },
    {
      id: 'gold_top_turret',
      description: '完美推塔',
      requirement: '推塔数≥4座',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'gold_top_damage',
      description: '超高输出',
      requirement: '输出占比≥30%',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.2,
      critical: true,
    },
    {
      id: 'gold_top_teamfight',
      description: '极高参团率',
      requirement: '参团率≥70%',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.9,
      critical: true,
    },
    {
      id: 'gold_top_kda',
      description: '顶级KDA',
      requirement: 'KDA≥8.0',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.3,
      critical: true,
    },
    {
      id: 'gold_top_low_death',
      description: '极少死亡',
      requirement: '死亡次数≤1次',
      type: 'increase',
      weight: 3.5,
      scoreBonus: 1.0,
      critical: true,
    },
    {
      id: 'gold_top_first_kill',
      description: '一血贡献',
      requirement: '参与一血',
      type: 'increase',
      weight: 3,
      scoreBonus: 0.8,
      critical: false,
    },
  ],
  decreaseTasks: [
    {
      id: 'gold_death_penalty',
      description: '死亡过多',
      requirement: '死亡次数>4次',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.5,
      critical: false,
    },
    {
      id: 'gold_low_participation',
      description: '参团率低',
      requirement: '参团率<40%',
      type: 'decrease',
      weight: 2,
      scoreBonus: -0.4,
      critical: false,
    },
    {
      id: 'gold_low_damage',
      description: '输出不足',
      requirement: '输出占比<15%',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.6,
      critical: true,
    },
    {
      id: 'gold_no_kill',
      description: '零击杀',
      requirement: '击杀数=0',
      type: 'decrease',
      weight: 3,
      scoreBonus: -1.0,
      critical: true,
    },
    {
      id: 'gold_high_death',
      description: '死亡爆炸',
      requirement: '死亡次数>6次',
      type: 'decrease',
      weight: 3,
      scoreBonus: -1.2,
      critical: true,
    },
    {
      id: 'gold_no_turret',
      description: '零推塔',
      requirement: '推塔数=0',
      type: 'decrease',
      weight: 2.5,
      scoreBonus: -0.7,
      critical: true,
    },
  ],
};

export const KOG_SCORING_CRITERIA: Record<Role, RoleScoringCriteria> = {
  exp_lane: EXP_LANE_TASKS,
  jungle: JUNGLE_TASKS,
  mid_lane: MID_LANE_TASKS,
  roam: ROAM_TASKS,
  gold_lane: GOLD_LANE_TASKS,
};

export function getGradeRequirement(grade: keyof typeof GRADE_REQUIREMENTS): GradeRequirement {
  return GRADE_REQUIREMENTS[grade];
}

export function getCriteriaByRole(role: Role): RoleScoringCriteria {
  return KOG_SCORING_CRITERIA[role];
}

export function getAllGrades(): GradeRequirement[] {
  return [
    GRADE_REQUIREMENTS.bronze,
    GRADE_REQUIREMENTS.silver,
    GRADE_REQUIREMENTS.gold,
    GRADE_REQUIREMENTS.top,
  ];
}
